### PR TITLE
S2S optimized version

### PR DESCRIPTION
**Pull request by sxlwar**
## Priority

Do you need reviewers to review this PR as soon as possible?

- [x] Medium

## Help Merge

Do you need any other people to merge it if all checks passed and reviews were approved?

- [x] Yes - Merge it immediately

## PR Type

What kind of change does this PR introduce?

- [x] Other... Please describe:

## Does this PR introduce a breaking change?

- [x] No

## Why do we need this pr?

fix some known performance issue

### CODE REVIEW

**Comment by 1022ranji** [comment]
Darwinia --> Crab-smart, 点击“Max”后转账仍失败
账号：2oXKyw2JuXf74toFspg8rFHuyWb8NedDJUXP9mDLqzNXeSA7
交易：https://darwinia.subscan.io/extrinsic/6516058-1
           https://darwinia.subscan.io/extrinsic/6516120-1
cc @xiaoch05 @sxlwar 

转账过程录屏：
https://user-images.githubusercontent.com/80877629/147441449-e5f8724e-eb91-46ce-bfbe-03173fe4923a.mov

**Review by WoeOm — APPROVED** [review]

**Comment by 1022ranji** [comment]
Darwinia --> Crab-smart, 点击“Max”后转账仍失败
账号：2oXKyw2JuXf74toFspg8rFHuyWb8NedDJUXP9mDLqzNXeSA7
交易：https://darwinia.subscan.io/extrinsic/6527667-2
cc @xiaoch05 @sxlwar

转账过程录屏：

https://user-images.githubusercontent.com/80877629/147518649-5290237a-3967-4bbd-a2d4-66bb8d159eae.mov

**Comment by WoeOm** [comment]
darwinia -> crab smart
费用包括： 
1. 跨链手续费：50 RING (链上实时查询） 
2. 交易手续费：可以通过 `extrinsic
            .paymentInfo(accountId)
            .then((info) => mountedRef.current && setDispatchInfo(info))
            .catch(console.error);` [https://github.com/polkadot-js/apps/blob/8a95b1a93b21cfd3a7cc0a24e1e08cb5022dc391/packages/react-signer/src/PaymentInfo.tsx](url) 预估出，也可以简单写一个固定的值 1 RING，当前实际约 0.02 RING。 跨链交易：[https://darwinia.subscan.io/extrinsic/6522761-1](url)


跨链完账户余额需要大于 api.consts.balances.existentialDeposit 尘埃账户的最小值，否则账号会被销毁，darwinia -> crab smart 跨链需要考虑这条吗？ @AurevoirXavier

**Comment by AurevoirXavier** [comment]
我觉得用户希望全部转出的都不考虑销毁

cc @xiaoch05

**Comment by xiaoch05** [comment]
> 我觉得用户希望全部转出的都不考虑是否影响到销毁
> 
> cc @xiaoch05

是的，应该只需要考虑这一笔交易是否有足够的余额支付gas费用，目前就留1个RING比较简单一点。

**Review by HackFisher — APPROVED** [review]

**Pull request merged**
