### PR TITLE
S2S formal bridge

### PR DESCRIPTION
**Pull request by sxlwar**
## Priority

Do you need reviewers to review this PR as soon as possible?

- [x] Medium

## Help Merge

Do you need any other people to merge it if all checks passed and reviews were approved?

- [x] Yes - Merge it immediately

## PR Type

What kind of change does this PR introduce?

- [x] Feature

## Does this PR introduce a breaking change?

- [x] No

### CODE REVIEW

**Comment by sxlwar** [comment]
image
replace the RPC  with your own to test the bridge

**Review by 1022ranji — COMMENTED** [review]
image
balance 足够，但是无法转账，querying 一直在转

**Comment by 1022ranji** [comment]
image
历史记录这里Token名称显示有问题 ，应该是RING

**Comment by 1022ranji** [comment]
image
正式桥的历史记录第三步还是有点问题 cc @xiaoch05 @fewensa

**Comment by 1022ranji** [comment]
Crab-smart > Darwinia 有余额，但无法转账，daily limit 显示 no limit
image

**Comment by 1022ranji** [comment]
Crab-smart > Darwinia 授权之后弹出的这个提示框有点奇怪，可以直接不显示
image

**Comment by 1022ranji** [comment]
Crab-smart > Darwinia 历史记录查询报错
image
0xe59261f6D4088BcD69985A3D369Ff14cC54EF1E5

**Review by 1022ranji — APPROVED** [review]

**Pull request merged**
